package client.net;

public enum MessageType {
    JOIN, MOVE, SHOOT, DEATH, DISCONNECT, STATE_UPDATE, SCORE_UPDATE,
    LOBBY_STATE, GAME_START, POWERUP_COLLECTED, POWERUP_RESPAWN, ROUND_END, ROUND_START
}

